### ISSUE TITLE
Angular data binding not working

### ISSUE THREAD

**Issue by Keith-Hon** [kriswme2/teamform-seed#10]
I have tried binding $scope.posts data from another event but failed. Anyone has some clues to do that?

**Comment by ycliae** [comment]
```
var currentRoomRef = Chatroom.chroom(  {{event.id}}  );
$scope.posts = $firebaseArray(currentRoomRef);
```

Would it work if you form a function of the above lines inside ChatroomCtrl and call it when changing the current event?

**Comment by Keith-Hon** [comment]
I tried 

var currentRoomRef = Chatroom.chroom(  "a" );
//
var currentRoomRef = Chatroom.chroom(  "b" );
//
and 
var currentRoomRef = Chatroom.chroom(  "default" );

$scope.posts = $firebaseArray(currentRoomRef);

but not working

also I made a simple test to bind a variable and display it inside the table, but still not work

**Comment by ycliae** [comment]
```
$timeout(function(){
    var currentRoomRef = Chatroom.chroom("b");
    $scope.posts = $firebaseArray(currentRoomRef);
}, 3000);
```

I ran this inside ChatroomCtrl and it changed to room "b" after 3sec.
It seems that $scope.posts just works in ChatroomCtrl, so we need to find a way to join other room by calling function from ChatroomCtrl.....

**Comment by Keith-Hon** [comment]
does it load the room "a" first? and then load room "b" after 3 secs?

**Comment by Keith-Hon** [comment]
I tried modifying the contents of $scope.posts and shown succesfully downloaded the content from firebase but the display does not update afterwards...

**Comment by ycliae** [comment]
> does it load the room "a" first? and then load room "b" after 3 secs?

Yes~

**Comment by Keith-Hon** [comment]
it works if do a timeout

**Comment by Keith-Hon** [comment]
i just tried to switch room after sending a message, but not works...
