### ISSUE TITLE
UI-bootstrap should not be included by directly putting it in js folder

### ISSUE THREAD

**Issue by kriswme2** [kriswme2/teamform-seed#22]
UI-bootstrap is a components, where the JS folder should store only Custom JavaScript by our team. Consider installing UI-bootstrap using CDN or using bower

**Comment by kriswme2** [comment]
It's already installed using bower, so it is included twice in the latest commit

**Comment by ycliae** [comment]
UI-bootstrap seems not be included twice as the latest commit contains another ng-app called Events.
https://github.com/kriswme2/teamform-seed/commit/58ac7edd80dc8db3a2d373096407403f41f9f2ee

**Comment by kriswme2** [comment]
Should make it a single page applications

**Comment by kriswme2** [comment]
Anyway, it shouldn't be included using bower or from CDN

eg. 
  <script type="text/javascript" src="components/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>
