### ISSUE TITLE
Add basic chatroom feature

### ISSUE THREAD

**Issue by ycliae** [kriswme2/teamform-seed#5]
- Chat in different room
- Show message in chronological order
- Send message to current room

**Comment by ycliae** [comment]
Pull request #6

**Comment by Keith-Hon** [comment]
Good! Do you have a data structure in mind that can be used for firebase?

**Comment by ycliae** [comment]
Sure~
All posts will be put in chatrooms/{{event.id}}/
Since there is no implemented factory for events so the event.id field is now meaningless in the existing data for testing.

**Comment by kriswme2** [comment]
firebase is already initialised in modules.js, so it shouldn't be re-initialize in adminform.js

**Comment by kriswme2** [comment]
Also, a new "Event module" is defined in adminform.js. A new module require some new html code in ng-app directive. 

In our apps, I suggest adding all features to one single modules (the teamform modules), as to make things simpler.
