### ISSUE TITLE
User name not shown correctly if main page is loaded first

### ISSUE THREAD

**Issue by Keith-Hon** [kriswme2/teamform-seed#86]
<img width="817" alt="screen shot 2016-11-26 at 17 37 47" src="https://cloud.githubusercontent.com/assets/23226987/20639480/3fc34116-b3ff-11e6-9059-e861801f70d9.png">

**Comment by Keith-Hon** [comment]
but it would work correctly if event page is browsed and refreshed.. e.g. 
http://localhost:8888/event/-KXUKnASwm6nYPq6HYnD and refresh page

**Comment by ycliae** [comment]
It is a dummy chatroom with eventID "a".
We have to change this landing page to a dashboard such as "event board" after authorizing.

**Comment by ycliae** [comment]
Problem solved. Please close this issue~

**Comment by Keith-Hon** [comment]
good
